config/routes.rb
Rails.application.routes.draw do
  get 'support/index'
  get 'timeline/index'
  get 'timelines', to: 'timeline#index'
  get 'admin', to: 'admin#index'
  get 'welcome/index'

  get 'api/get_all_json', to: 'api#get_covid_cases'
  # get 'covid_cases/get_all_json', to: 'covid_cases#get_all_json'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :covid_cases
  resources :timelines

  root 'covid_cases#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/covid_case.rb
class CovidCase < ApplicationRecord
  has_many :timelines
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  belongs_to :covid_case
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: ENV["RAILS_ADMIN_USERNAME"] ? ENV["RAILS_ADMIN_USERNAME"] : "dhh", password: ENV["RAILS_ADMIN_PASSWORD"] ? ENV["RAILS_ADMIN_PASSWORD"] : "secret"
  def index
    GenerateChartStaticFilesJob.perform_later
    render plain: "RUN"
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  def get_covid_cases
    @covid_cases = CovidCase.all
    render json: @covid_cases
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/covid_cases_controller.rb
class CovidCasesController < ApplicationController

  around_action :switch_locale

  def index
    I18n.default_locale = :th
    @display_chart = {
      :by_occupation => true,
      :by_age => true,
      :by_gender => true,
      :by_province => true
    }

    @menu = {"menu1" => "active"}

    @covid_cases = CovidCase.order(no: :desc).limit(10)
    @oldest = CovidCase.where("age >= 0").maximum(:age)
    @youngest = CovidCase.where("age >= 0").minimum(:age)
    @age_avg = CovidCase.where("age >= 0").average("age")
    @latest_date = CovidCase.order(announce_date: :desc).first
    @total_cases = CovidCase.maximum(:no)

    if @youngest < 1
      @youngest = (@youngest * 12)
    end
    
    @title = "สถิติภาพรวมของประเทศไทย"
    
    # render 'covid_cases/index', :locals => {@covid_cases => @covid_cases, @display_chart => @display_chart}
  end

  def new
  end

  def create

    @covid_case = CovidCase.new(user_params)

    @covid_case.save
    redirect_to @covid_case
  end

  def show
    @covid_case = CovidCase.find(params[:id])
  end

  def get_all_json
    @covid_cases = CovidCase.all
    render json: @covid_cases
  end

  private
    def user_params
      params.require(:covid_case).permit(:no, :age, :sex, :nation, :occ_new, :province, :risk, :district, :notification_date, :announce_date)
    end

    def switch_locale(&action)
      locale = params[:locale] || I18n.default_locale
      I18n.with_locale(locale, &action)
    end
end


# -- select occ_new, count(no) as total from covid_cases where occ_new <> 'ไม่ระบุ' group by occ_new order by count(no) desc limit 10;
# select province, count(no) as total from covid_cases where province <> 'ไม่ระบุ' group by province order by count(no) desc limit 10;

app/controllers/support_controller.rb
class SupportController < ApplicationController
  def index
  end
end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  def index
    @title = "Timeline ผู้ติดเชื้อ"
    @menu = {"menu2" => "active"}
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/covid_cases_helper.rb
module CovidCasesHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/covid_cases/index.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark"><%= @title %></h1>
        <p>ข้อมูลวันที่: <%= l @latest_date.announce_date, format: '%d %b %Y' %> (ข้อมูลนี้เป็นเพียงภาพรวม ไม่เหมาะสำหรับใช้ในการอ้างอิง)</p>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">หน้าหลัก</a></li>
          <li class="breadcrumb-item active"><%= @title %></li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <%# total %>
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-danger">
          <div class="inner">
            <h3><%= number_with_delimiter @total_cases %></h3>

            <p><%= t 'labels.infected_total'%></p>
          </div>
          <div class="icon">
            <i class="fas fa-user-circle"></i>
          </div>
          <a href="#" class="small-box-footer"><i class="fas fa-minus"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <%# oldest %>
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-indigo">
          <div class="inner">
            <h3><%= @oldest.ceil %><sup style="font-size: 20px"><%= t 'labels.age_year'%></sup></h3>

            <p><%= t 'labels.age_oldest'%></p>
          </div>
          <div class="icon">
            <i class="fas fa-user"></i>
          </div>
          <a href="#" class="small-box-footer"><i class="fas fa-minus"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <%# youngest %>
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
          <div class="inner">
            <h3><%= @youngest.ceil %><sup style="font-size: 20px">เดือน</sup></h3>

            <p><%= t 'labels.age_youngest' %></p>
          </div>
          <div class="icon">
            <i class="fas fa-baby"></i>
          </div>
          <a href="#" class="small-box-footer"><i class="fas fa-minus"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <%# average %>
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-warning">
          <div class="inner">
            <h3><%= number_with_precision @age_avg, :precision => 1 %><sup style="font-size: 20px"><%= t 'labels.age_year'%></sup></h3>

            <p><%= t 'labels.age_avg' %></p>
          </div>
          <div class="icon">
            <i class="fas fa-tachometer-alt"></i>
          </div>
          <a href="#" class="small-box-footer"><i class="fas fa-minus"></i></a>
        </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->
    <!-- Main row -->
    <div class="row">
      <!-- Left col -->
      <section class="col-lg-6 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-chart-pie mr-1"></i>
              <%= t 'labels.by_gender' %>
            </h3>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content p-0">
              <!-- Morris chart - Sales -->
              <div class="chart tab-pane active" id="revenue-chart" style="position: relative;">
                <%# <canvas id="revenue-chart-canvas" height="300" style="height: 300px;"></canvas> %>
                <canvas id="by-gender-chart"></canvas>
              </div>
            </div>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->
      </section>
      <section class="col-lg-6 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-chart-pie mr-1"></i>
              สถิติผู้ติดเชื้อแบ่งตามช่วงอายุ
            </h3>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content p-0">
              <!-- Morris chart - Sales -->
              <div class="chart tab-pane active" id="revenue-chart" style="position: relative;">
                <%# <canvas id="revenue-chart-canvas" height="300" style="height: 300px;"></canvas> %>
                <canvas id="by-age-chart"></canvas>
              </div>
            </div>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->
      </section>
      <section class="col-lg-6 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-chart-pie mr-1"></i>
              <%= t 'labels.by_occupation'%> *ข้อมูลถึงวันที่ 28 มี.ค. 63
            </h3>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content p-0">
              <!-- Morris chart - Sales -->
              <div class="chart tab-pane active" id="revenue-chart" style="position: relative;">
                <%# <canvas id="revenue-chart-canvas" height="300" style="height: 300px;"></canvas> %>
                <canvas id="by-occupation-chart"></canvas>
              </div>
            </div>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->
      </section>
      <section class="col-lg-6 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-chart-pie mr-1"></i>
              <%= t 'labels.by_province'%>
            </h3>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content p-0">
              <!-- Morris chart - Sales -->
              <div class="chart tab-pane active" id="revenue-chart" style="position: relative;">
                <%# <canvas id="revenue-chart-canvas" height="300" style="height: 300px;"></canvas> %>
                <canvas id="by-province-chart"></canvas>
              </div>
            </div>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->
      </section>
      <section class="col-lg-6 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-chart-pie mr-1"></i>
              <%= t 'labels.by_province_without_bkk'%>
            </h3>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content p-0">
              <!-- Morris chart - Sales -->
              <div class="chart tab-pane active" id="revenue-chart" style="position: relative;">
                <%# <canvas id="revenue-chart-canvas" height="300" style="height: 300px;"></canvas> %>
                <canvas id="by-province-without-bkk"></canvas>
              </div>
            </div>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->
      </section>
      <section class="col-lg-6 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-chart-pie mr-1"></i>
              กราฟเปรียบเทียบผู้ติดเชื้อสะสมในกทมและต่างจังหวัด <span class="right badge badge-danger">New</span>
            </h3>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content p-0">
              <!-- Morris chart - Sales -->
              <div class="chart tab-pane active" id="revenue-chart" style="position: relative;">
                <%# <canvas id="revenue-chart-canvas" height="300" style="height: 300px;"></canvas> %>
                <canvas id="by-bkk-and-nonbkk-time-serie"></canvas>
              </div>
            </div>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->
      </section>
      <section class="col-lg-6 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-chart-pie mr-1"></i>
              สถิติผู้ติดเชื้อแบ่งคนไทยและต่างชาติ
            </h3>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content p-0">
              <!-- Morris chart - Sales -->
              <div class="chart tab-pane active" id="revenue-chart" style="position: relative;">
                <%# <canvas id="revenue-chart-canvas" height="300" style="height: 300px;"></canvas> %>
                <canvas id="by-country-th-and-non"></canvas>
              </div>
            </div>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->
      </section>
      <section class="col-lg-6 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-chart-pie mr-1"></i>
              <%= t 'labels.by_country_without_thailand'%>
            </h3>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content p-0">
              <!-- Morris chart - Sales -->
              <div class="chart tab-pane active" id="revenue-chart" style="position: relative;">
                <%# <canvas id="revenue-chart-canvas" height="300" style="height: 300px;"></canvas> %>
                <canvas id="by-country-without-thailand"></canvas>
              </div>
            </div>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->
      </section>
      <section class="col-lg-12 connectedSortable">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-chart-pie mr-1"></i>
              แหล่งข้อมูลอ้างอิง
            </h3>
          </div><!-- /.card-header -->
          <div class="card-body">
            <ul>
              <li><a href="https://data.go.th/dataset/covid-19-daily" target="_blank">https://data.go.th/dataset/covid-19-daily</a></li>
            </ul>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->
      </section>
      <!-- /.Left col -->
    </div>
    <!-- /.row (main row) -->
  </div><!-- /.container-fluid -->
</section>


<script src="/charts/by-gender.js"></script>
<script src="/charts/by-occupation.js"></script>
<script src="/charts/by-age.js"></script>
<script src="/charts/by-province.js"></script>
<script src="/charts/by-country-th-and-non.js"></script>
<script src="/charts/by-province-without-bkk.js"></script>
<script src="/charts/by-country-without-thailand.js"></script>
<script src="/charts/by-bkk-and-nonbkk-time-serie.js"></script>

app/views/covid_cases/new.html.erb
<h1>New Covid case</h1>

<%= form_with scope: :covid_case, url: covid_cases_path, local: true do |form| %>
  <p>
    <%= form.label :no %>
    <%= form.number_field :no, step: 1 %>
  </p>
  <p>
    <%= form.label :age %>
    <%= form.number_field :age, step: 1%>
  </p>
  <p>
    <%= form.label :sex %>
    <%= form.select :sex, ['ชาย', 'หญิง', 'ไม่ระบุ'] %>
  </p>
  <p>
    <%= form.label :nation %>
    <%= form.text_field :nation %>
  </p>
  <p>
    <%= form.label :occ_new %>
    <%= form.text_field :occ_new %>
  </p>
  <p>
    <%= form.label :province %>
    <%= form.text_field :province %>
  </p>
  <p>
    <%= form.label :risk %><br>
    <%= form.text_area :risk %>
  </p>
  <p>
    <%= form.label :district %>
    <%= form.text_field :district %>
  </p>
  <p>
    <%= form.label :notification_date %>
    <%= form.date_field :notification_date %>
  </p>
  <p>
    <%= form.label :announce_date %>
    <%= form.date_field :announce_date %>
  </p>
  <p><%= form.submit %></p>
<% end %>

app/views/covid_cases/show.html.erb
<h1>Case No: <%= @covid_case.no %></h1>
<p>
  <strong>Age: </strong>
  <%= @covid_case.age %>
</p>
<p>
  <strong>Sex: </strong>
  <%= @covid_case.sex %>
</p>
<p>
  <strong>Nation: </strong>
  <%= @covid_case.nation %>
</p>
<p>
  <strong>Occupation: </strong>
  <%= @covid_case.occ_new %>
</p>
<p>
  <strong>PRovince: </strong>
  <%= @covid_case.province %>
</p>
<p>
  <strong>Risk: </strong>
  <%= @covid_case.risk %>
</p>
<p>
  <strong>District: </strong>
  <%= @covid_case.district %>
</p>
<p>
  <strong>Notification date: </strong>
  <%= @covid_case.notification_date %>
</p>
<p>
  <strong>Announce date: </strong>
  <%= @covid_case.announce_date %>
</p>
<h2>Timeline:</h2>

app/views/support/index.html.erb
<h1>Support#index</h1>
<p>Find me in app/views/support/index.html.erb</p>

app/views/timeline/index.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark"><%= @title %></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="/">หน้าหลัก</a></li>
          <li class="breadcrumb-item active"><%= @title %></li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <!-- ./col -->
      <!-- ./col -->
      <%# average %>
      <div class="col-lg-12 col-12">
        <!-- small box -->
        <h1 style="text-align: center">เร็วๆ นี้</h1>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->
    <!-- /.row (main row) -->
  </div><!-- /.container-fluid -->
</section>

app/views/welcome/index.html.erb
<h1>Covid-19 Dashboard</h1>
<%= link_to  "Covid cases", covid_cases_path %>